set(PULSEAUDIO_FOUND TRUE)

set(PULSEAUDIO_VERSION_MAJOR 17)
set(PULSEAUDIO_VERSION_MINOR 0)
set(PULSEAUDIO_VERSION 17.0)
set(PULSEAUDIO_VERSION_STRING "17.0")

find_path(PULSEAUDIO_INCLUDE_DIR pulse/pulseaudio.h HINTS "/home/conda/feedstock_root/build_artifacts/pulseaudio-split_1705689856413/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include")
find_library(PULSEAUDIO_LIBRARY NAMES pulse libpulse HINTS "/home/conda/feedstock_root/build_artifacts/pulseaudio-split_1705689856413/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib")
find_library(PULSEAUDIO_MAINLOOP_LIBRARY NAMES pulse-mainloop-glib libpulse-mainloop-glib HINTS "/home/conda/feedstock_root/build_artifacts/pulseaudio-split_1705689856413/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib")
